* most of the Makefile work merged from GrAnd's branch
git-svn-id: https://tools.assembla.com/svn/chdk/trunk@40 6794e30b-3f2a-0410-a806-a2bbca1c07ff

diff --git a/platform/a710/sub/100a/Makefile b/platform/a710/sub/100a/Makefile
--- a/platform/a710/sub/100a/Makefile
+++ b/platform/a710/sub/100a/Makefile
@@ -4,21 +4,47 @@ include $(topdir)makefile.inc
 
 all: libplatformsub.a
 
-OBJS=boot.o stubs_min.o stubs_auto.o stubs_entry.o stubs_entry_2.o lib.o
+TARGET_PRIMARY = PRIMARY.BIN
+OBJS=boot.o stubs_min.o stubs_auto.o stubs_entry.o lib.o stubs_entry_2.o
 
 libplatformsub.a: $(OBJS)
 
 clean:
-	rm -f *.o *.a
+	rm -f $(OBJS) libplatformsub.a stubs_entry.S.err stubs_not_found_names.err
 
 stubs_auto.S: boot.c
+	@echo $< \-\> $@
 # UNIX shell magick )
 	cat $< | \
 	    grep 'BL\?[[:space:]]*sub_[0-9A-Fa-f]' | \
 	    sed 's/.*sub_\([0-9A-Fa-f]*\).*/\1/' | \
-	    sort | uniq | \
+	    $(SORT) | uniq | \
 	    awk 'BEGIN {print "/* THIS FILE IS GENERATED */\n#include \"stubs_asm.h\"\n"} \
 		{printf("STUB(%s)\n",$$1)}' > stubs_auto.S
 
-stubs_entry.S:
-	$(topdir)tools/finsig $(TARGET_PRIMARY) $(ROMBASEADDR) > stubs_entry.S
+stubs_entry.S: $(topdir)tools/finsig$(EXE) $(TARGET_PRIMARY)
+	@echo \-\> $@
+	rm -f stubs_entry.S.err
+	if [ -s $(TARGET_PRIMARY) ] ; then \
+	  $(topdir)tools/finsig $(TARGET_PRIMARY) $(ROMBASEADDR) > stubs_entry.S ; \
+	else \
+	  echo CAUTION! \'stubs_entry.S\' is not uptated due to target firmware binary not found! ; \
+	  touch stubs_entry.S ; \
+	fi ; \
+	if [ "X`grep 'ERROR' stubs_entry.S`" != "X" ] ; then \
+	  grep "ERROR" stubs_entry.S | sed -r "s/\/\/ ERROR: ([^ ]+) is not found.*/\1/" | $(SORT) | uniq > stubs_nf.names ; \
+	  grep -E "NH?STUB" stubs_entry_2.S | sed -r "s/ *NH?STUB\( *([^ ,]+).*/\1/" | $(SORT) | uniq > stubs_mn.names ; \
+	  comm -23 stubs_nf.names stubs_mn.names > stubs_not_found_names.err ; \
+	  rm -f stubs_nf.names stubs_mn.names ; \
+	  if [ -s stubs_not_found_names.err ] ; then \
+	    echo ERROR! There are unresolved addresses in \'stubs_entry.S\' \($(PLATFORM)-$(PLATFORMSUB)\) for the following names: ; \
+	    cat stubs_not_found_names.err ; \
+	    echo Please, add them into \'stubs_entry_2.S\' manually! ; \
+	    mv stubs_entry.S stubs_entry.S.err ; \
+	    exit 1 ; \
+	  fi ; \
+	  rm -f stubs_not_found_names.err ; \
+	fi
+
+$(TARGET_PRIMARY):
+	touch $(TARGET_PRIMARY)
